### ISSUE TITLE
Where does cn=admin,dc=example,dc=com coming from?!

### ISSUE THREAD

**Issue by mathieumd** [debops/ansible-slapd#42]
I set the baseDN admin to `cn=Manager,dc=example,dc=com`, but I still get a `cn=admin,dc=example,dc=com` created too. But:

1. I can't find where `cn=admin` is coming from;
2. I can't even log in as `cn=admin`, while login as `cn=Manager` is working.

Related variables I set up are as follow:
```yaml
slapd_basedn: 'dc=example,dc=com'
slapd_basepw: '{{"../credentials/" + inventory_hostname + "/slapd" }}'
slapd_basedn_admin: '{{"cn=Manager," + slapd_basedn}}'
slapd_basedn_admin_basepw: '{{slapd_basepw + "/" + slapd_basedn + "/" + slapd_basedn_admin }}'
```

The `cn=admin,dc=example,dc=com` account is created with a `description` attribute set to `LDAP administrator` and it's operational attribute `creatorsName` is set to `cn=admin,dc=example,dc=com`.

The `cn=Manager,dc=example,dc=com` password is saved correctly (into `../credentials/testvm/slapd/dc=example,dc=com/cn=Manager,dc=example,dc=com.password`), and it does works to connect to slapd.

However, while the `cn=admin` password is saved under `secret` path as expected (under `secret/ldap/example.com/credentials/ldap.example.com/cn=admin,dc=example,dc=com.password`), it doesn't work for login. And it's the same value as the `cn=Manager`'s password, which shouldn't be the case (as far as I'm understanding the role).

Something looks fishy, but I'm a little bit lost in all variables, roles and dependencies involved...

According to `.galaxy_install_info` data:

- debops.slapd: install_date: 'Thu Oct 12 14:39:33 2017', version: master
- debops.secret: install_date: 'Thu Oct 12 14:39:38 2017', version: v0.3.1
